### ISSUE TITLE
Wrong URL in REPO

### ISSUE THREAD

**Issue by europ** [astaruch/slovakrail-ticket-script#4]
Please, can you change the URL in your repository description to https://www.zssk.sk/? The URL does not work and the python script works with https://www.zssk.sk/ as you can see [here](https://github.com/astaruch/slovakrail-ticket-script/blob/f8b2eff0b761880afd3f8d34a968e9024aa47dff/buy_ticket.py#L73).

**Comment by europ** [comment]
**Update**: The new URL should be https://ikvc.slovakrail.sk/esales/search.

**Comment by astaruch** [comment]
Fixed
