### ISSUE TITLE
Outdate e-shop

### ISSUE THREAD

**Issue by Cropi** [astaruch/slovakrail-ticket-script#5]
The script is working with old e-shop at:
http://www.zssk.sk/
that redirects you to:
https://ikvc.slovakrail.sk/inet-sales-web/pages/connection/search.xhtml

**The e-shop is deprecated and it will be closed soon** as you can see:

```
Už čoskoro vypneme starú verziu internetového obchodu.
Prejdite už teraz na nový spôsob nákupu cestovného lístka.
```

A new e-shop should be used instead:
https://ikvc.slovakrail.sk/esales/search

**Comment by europ** [comment]
@astaruch if #3 will be merged into master I will open a new PR which will fix this. I have already integrated this new e-shop into the script. As you can see [here (github.com/europ/slovakrail-ticket-script/tree/zssk_page_upgrade)](https://github.com/europ/slovakrail-ticket-script/tree/zssk_page_upgrade) I am working on it and it is nearly done.
